### ISSUE TITLE
installer does not work 

### ISSUE THREAD

**Issue by laurianops** [HeLiBloks/exiftool-zsh-completion#1]
sudo make install not work
distro Fedora 27.

**Comment by HeLiBloks** [comment]
It seems Fedora uses a different directory structure than Ubuntu.
I have changed the Makefile to be more platform independent.
Otherwise try to append the _exiftool file path to the ```$fpath``` in your .zshrc
it should look some thing like this:
```   fpath=(/home/$USER/myZshellCompletionFiles/exiftool-zsh-completion/ $fpath)```

**Comment by laurianops** [comment]
Thanks
